In [1]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

In [3]:
train = pd.read_csv('titanic/train.csv')
train.head(10)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   
5            6         0       3   
6            7         0       1   
7            8         0       3   
8            9         1       3   
9           10         1       2   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   
5                                   Moran, Mr. James    male   NaN      0   
6                            McCarthy, Mr. Timothy J    male  54.0      0   
7                     Palsson, Master. Gosta Leonard    male   2.0      3   
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0   
9                Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S  
5      0            330877   8.4583   NaN        Q  
6      0             17463  51.8625   E46        S  
7      1            349909  21.0750   NaN        S  
8      2            347742  11.1333   NaN        S  
9      0            237736  30.0708   NaN        C

In [4]:
train = train.set_index('PassengerId')

In [7]:
train

Survived  Pclass  \
PassengerId                     
1                   0       3   
2                   1       1   
3                   1       3   
4                   1       1   
5                   0       3   
...               ...     ...   
887                 0       2   
888                 1       1   
889                 0       3   
890                 1       1   
891                 0       3   

                                                          Name     Sex   Age  \
PassengerId                                                                    
1                                      Braund, Mr. Owen Harris    male  22.0   
2            Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0   
3                                       Heikkinen, Miss. Laina  female  26.0   
4                 Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0   
5                                     Allen, Mr. William Henry    male  35.0   
...                                                        ...     ...   ...   
887                                      Montvila, Rev. Juozas    male  27.0   
888                               Graham, Miss. Margaret Edith  female  19.0   
889                   Johnston, Miss. Catherine Helen "Carrie"  female   NaN   
890                                      Behr, Mr. Karl Howell    male  26.0   
891                                        Dooley, Mr. Patrick    male  32.0   

             SibSp  Parch            Ticket     Fare Cabin Embarked  
PassengerId                                                          
1                1      0         A/5 21171   7.2500   NaN        S  
2                1      0          PC 17599  71.2833   C85        C  
3                0      0  STON/O2. 3101282   7.9250   NaN        S  
4                1      0            113803  53.1000  C123        S  
5                0      0            373450   8.0500   NaN        S  
...            ...    ...               ...      ...   ...      ...  
887              0      0            211536  13.0000   NaN        S  
888              0      0            112053  30.0000   B42        S  
889              1      2        W./C. 6607  23.4500   NaN        S  
890              0      0            111369  30.0000  C148        C  
891              0      0            370376   7.7500   NaN        Q  

[891 rows x 11 columns]

In [8]:
train.columns

Index(['Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch', 'Ticket',
       'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [9]:
target = 'Survived'

In [10]:
y = train[target]
X = train.drop(target, axis=1)

In [11]:
X.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 891 entries, 1 to 891
Data columns (total 10 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Pclass    891 non-null    int64  
 1   Name      891 non-null    object 
 2   Sex       891 non-null    object 
 3   Age       714 non-null    float64
 4   SibSp     891 non-null    int64  
 5   Parch     891 non-null    int64  
 6   Ticket    891 non-null    object 
 7   Fare      891 non-null    float64
 8   Cabin     204 non-null    object 
 9   Embarked  889 non-null    object 
dtypes: float64(2), int64(3), object(5)
memory usage: 76.6+ KB


In [12]:
X.drop(['Cabin', 'Name', 'Ticket'], axis=1, inplace=True)

In [13]:
X.columns

Index(['Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare', 'Embarked'], dtype='object')

In [14]:
X.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 891 entries, 1 to 891
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Pclass    891 non-null    int64  
 1   Sex       891 non-null    object 
 2   Age       714 non-null    float64
 3   SibSp     891 non-null    int64  
 4   Parch     891 non-null    int64  
 5   Fare      891 non-null    float64
 6   Embarked  889 non-null    object 
dtypes: float64(2), int64(3), object(2)
memory usage: 55.7+ KB


In [17]:
mean_age = X['Age'].mean()

In [18]:
X['Age'] = X['Age'].fillna(mean_age)
X['Age'].unique()

array([22.        , 38.        , 26.        , 35.        , 29.69911765,
       54.        ,  2.        , 27.        , 14.        ,  4.        ,
       58.        , 20.        , 39.        , 55.        , 31.        ,
       34.        , 15.        , 28.        ,  8.        , 19.        ,
       40.        , 66.        , 42.        , 21.        , 18.        ,
        3.        ,  7.        , 49.        , 29.        , 65.        ,
       28.5       ,  5.        , 11.        , 45.        , 17.        ,
       32.        , 16.        , 25.        ,  0.83      , 30.        ,
       33.        , 23.        , 24.        , 46.        , 59.        ,
       71.        , 37.        , 47.        , 14.5       , 70.5       ,
       32.5       , 12.        ,  9.        , 36.5       , 51.        ,
       55.5       , 40.5       , 44.        ,  1.        , 61.        ,
       56.        , 50.        , 36.        , 45.5       , 20.5       ,
       62.        , 41.        , 52.        , 63.        , 23.5 

In [19]:
X['Embarked'].value_counts()

S    644
C    168
Q     77
Name: Embarked, dtype: int64

In [21]:
embarked_mode = X['Embarked'].mode()[0]
X['Embarked'] = X['Embarked'].fillna(embarked_mode)
X['Embarked'].value_counts()

S    646
C    168
Q     77
Name: Embarked, dtype: int64

In [22]:
X['Sex'].value_counts()

male      577
female    314
Name: Sex, dtype: int64

In [26]:
X['Sex'] = (X['Sex'] == 0).astype(int)

In [27]:
X['Sex'].value_counts()

1    577
0    314
Name: Sex, dtype: int64

In [28]:
X = pd.get_dummies(X)

In [29]:
X

Pclass  Sex        Age  SibSp  Parch     Fare  Embarked_C  \
PassengerId                                                              
1                 3    1  22.000000      1      0   7.2500           0   
2                 1    0  38.000000      1      0  71.2833           1   
3                 3    0  26.000000      0      0   7.9250           0   
4                 1    0  35.000000      1      0  53.1000           0   
5                 3    1  35.000000      0      0   8.0500           0   
...             ...  ...        ...    ...    ...      ...         ...   
887               2    1  27.000000      0      0  13.0000           0   
888               1    0  19.000000      0      0  30.0000           0   
889               3    0  29.699118      1      2  23.4500           0   
890               1    1  26.000000      0      0  30.0000           1   
891               3    1  32.000000      0      0   7.7500           0   

             Embarked_Q  Embarked_S  
PassengerId                          
1                     0           1  
2                     0           0  
3                     0           1  
4                     0           1  
5                     0           1  
...                 ...         ...  
887                   0           1  
888                   0           1  
889                   0           1  
890                   0           0  
891                   1           0  

[891 rows x 9 columns]

In [31]:
X['Pclass'] = X['Pclass'].astype(str)

In [32]:
X.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 891 entries, 1 to 891
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Pclass      891 non-null    object 
 1   Sex         891 non-null    int64  
 2   Age         891 non-null    float64
 3   SibSp       891 non-null    int64  
 4   Parch       891 non-null    int64  
 5   Fare        891 non-null    float64
 6   Embarked_C  891 non-null    uint8  
 7   Embarked_Q  891 non-null    uint8  
 8   Embarked_S  891 non-null    uint8  
dtypes: float64(2), int64(3), object(1), uint8(3)
memory usage: 51.3+ KB


In [33]:
X = pd.get_dummies(X)

In [34]:
X.head()

Sex   Age  SibSp  Parch     Fare  Embarked_C  Embarked_Q  \
PassengerId                                                             
1              1  22.0      1      0   7.2500           0           0   
2              0  38.0      1      0  71.2833           1           0   
3              0  26.0      0      0   7.9250           0           0   
4              0  35.0      1      0  53.1000           0           0   
5              1  35.0      0      0   8.0500           0           0   

             Embarked_S  Pclass_1  Pclass_2  Pclass_3  
PassengerId                                            
1                     1         0         0         1  
2                     0         1         0         0  
3                     1         0         0         1  
4                     1         1         0         0  
5                     1         0         0         1

In [35]:
X_train, X_valid, y_train, y_valid = train_test_split(X, y, test_size=1/4, random_state=42)

In [36]:
X_train.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 668 entries, 299 to 103
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Sex         668 non-null    int64  
 1   Age         668 non-null    float64
 2   SibSp       668 non-null    int64  
 3   Parch       668 non-null    int64  
 4   Fare        668 non-null    float64
 5   Embarked_C  668 non-null    uint8  
 6   Embarked_Q  668 non-null    uint8  
 7   Embarked_S  668 non-null    uint8  
 8   Pclass_1    668 non-null    uint8  
 9   Pclass_2    668 non-null    uint8  
 10  Pclass_3    668 non-null    uint8  
dtypes: float64(2), int64(3), uint8(6)
memory usage: 35.2 KB


In [53]:
lr = LogisticRegression(solver='lbfgs', max_iter=7600)

In [54]:
lr.fit(X_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=7600,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [55]:
y_pred = lr.predict(X_valid)
y_pred

array([0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0,
       1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0,
       0, 1, 0])

In [56]:
from sklearn.metrics import accuracy_score

In [57]:
accuracy_score(y_valid, y_pred)

0.8026905829596412

In [58]:
y_pred_train = lr.predict(X_train)

In [59]:
accuracy_score(y_train, y_pred_train)

0.8083832335329342

In [60]:
y_proba = lr.predict_proba(X_valid)

In [61]:
y_proba

array([[0.88842785, 0.11157215],
       [0.73093197, 0.26906803],
       [0.87040093, 0.12959907],
       [0.0898291 , 0.9101709 ],
       [0.25114841, 0.74885159],
       [0.07809052, 0.92190948],
       [0.3332392 , 0.6667608 ],
       [0.90541505, 0.09458495],
       [0.24443399, 0.75556601],
       [0.10299525, 0.89700475],
       [0.69416668, 0.30583332],
       [0.93498524, 0.06501476],
       [0.62466754, 0.37533246],
       [0.84821583, 0.15178417],
       [0.75880267, 0.24119733],
       [0.07872818, 0.92127182],
       [0.72731434, 0.27268566],
       [0.33315487, 0.66684513],
       [0.70273873, 0.29726127],
       [0.70632678, 0.29367322],
       [0.88408023, 0.11591977],
       [0.6426365 , 0.3573635 ],
       [0.39823608, 0.60176392],
       [0.86969651, 0.13030349],
       [0.89852549, 0.10147451],
       [0.92826309, 0.07173691],
       [0.56636264, 0.43363736],
       [0.72856911, 0.27143089],
       [0.91449584, 0.08550416],
       [0.42637592, 0.57362408],
       [0.

In [62]:
X_train.to_pickle('X_train.pkl')
X_valid.to_pickle('X_valid.pkl')

y_train.to_pickle('y_train.pkl')
y_valid.to_pickle('y_valid.pkl')

In [63]:
!ls

LICENSE             X_valid.pkl         les_6_video_1.ipynb y_train.pkl
README.md           les_2.ipynb         les_6_video_2.ipynb y_valid.pkl
X_train.pkl         les_4.ipynb         titanic
